[[group]]
markets = [
"DRAf8QxQY86h7yeHdo9GytXAF6GoTTT8oZjknwXV6dCS", #PENGUIN-SOL Pump AMM
"LJGCprfvx4qZVXktL24CLArGwzpAsQXjq5AQFa5w6WT", #PENGUIN-SOL Meteora DLMM
"4qxSqMh6iEdbdvtMp8r5MK2psAGKNk57PfGeVo2VhczQ", #WhiteWhale-SOL Pump AMM
"EFeysyAM1mB8oT3FpK9xZsZRc8JRaj24g1XDSrg1VjSu", #WhiteWhale-SOL Meteora DLMM
"GZMwW4Fzszw1BmfResgJKA19CMymsGFcfeqxXsBzDp6w", #METALS-SOL Pump AMM
"DbH7vi3paSR9g5xc1hL5zRAKM69TZiUSNfzw6wzbvZxU", #METALS-SOL Meteora DLMM
]